/*
  Warnings:

  - Added the required column `sectorId` to the `CompanyProfile` table without a default value. This is not possible if the table is not empty.

*/
-- CreateEnum
CREATE TYPE "SectorType" AS ENUM ('TECNOLOGIA', 'SOFTWARE', 'INTELIGENCIA_ARTIFICIAL', 'TELECOMUNICACOES', 'SEGURANCA_CIBERNETICA', 'FINANCAS', 'BANCOS', 'SEGUROS', 'INVESTIMENTOS', 'CONSULTORIA', 'SAUDE', 'FARMACEUTICA', 'BIOTECNOLOGIA', 'EQUIPAMENTOS_MEDICOS', 'HOSPITALIDADE_MEDICA', 'VAREJO', 'E_COMMERCE', 'ALIMENTOS_E_BEBIDAS', 'MODA', 'PRODUTOS_DE_CONSUMO', 'INDUSTRIA', 'AUTOMOTIVA', 'AEROESPACIAL', 'QUIMICA', 'MAQUINARIO_PESADO', 'MANUFATURA', 'ENERGIA', 'PETROLEO_E_GAS', 'ENERGIA_RENOVAVEL', 'MINERACAO', 'AGRICULTURA', 'PESCA', 'SERVICOS', 'TRANSPORTE', 'LOGISTICA', 'CONSTRUCAO', 'IMOBILIARIO', 'TURISMO', 'HOTEIS', 'COMUNICACAO', 'MIDIA', 'PUBLICIDADE_E_MARKETING', 'ENTRETENIMENTO', 'JOGOS', 'EDUCACAO', 'ENSINO_SUPERIOR', 'ENSINO_BASICO', 'ED_TECH', 'GOVERNO', 'ORGANIZACAO_NAO_GOVERNAMENTAL', 'OUTRO_SETOR');

-- AlterTable
ALTER TABLE "CompanyProfile" ADD COLUMN     "sectorId" TEXT NOT NULL;

-- CreateTable
CREATE TABLE "CompanySector" (
    "id" TEXT NOT NULL,
    "name" "SectorType" NOT NULL,

    CONSTRAINT "CompanySector_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "CompanySector_name_key" ON "CompanySector"("name");

-- AddForeignKey
ALTER TABLE "CompanyProfile" ADD CONSTRAINT "CompanyProfile_sectorId_fkey" FOREIGN KEY ("sectorId") REFERENCES "CompanySector"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
