export const packageSeeds = [
  {
    name: "Pacote Básico",
    description: "Ideal para escritórios pequenos, lojas ou residências sem empresariais.",
    employees: 5, 
    price: 426000.00,
    isActive: true,
    isPopular: false,
    details: [
      "Equipa de até 5 profissionais",
      "Uniformes incluídos",
      "Supervisão periódica",
      "Gestão administrativa completa",
    ],
  },
  {
    name: "Pacote Profissional",
    description: "Para médias empresas, clínicas, showrooms ou escritórios de médio porte.",
    employees: 10, 
    price: 1011750.00,
    isActive: true,
    isPopular: true,
    details: [
      "Equipa de até 10 profissionais",
      "Uniformes incluídos",
      "Supervisão semanal",
      "Equipamento básico de limpeza",
      "Substituição em caso de falta",
      "Gestão administrativa completa",
      "Plano de fidelização com descontos",
    ],
  },
  {
    name: "Pacote Premium",
    description: "Ideal para escolas e clínicas maiores, com serviço de alta dedicação e detalhe.",
    employees: 15,
    price: 1917000.00,
    isActive: true,
    isPopular: false,
    details: [
      "Equipa de até 15 profissionais",
      "Uniformes incluídos",
      "Supervisão dedicada",
      "Gestão administrativa completa",
      "Relatório detalhado mensal",
      "Substituição imediata",
      "Equipamento de limpeza",
      "Produtos de limpeza incluídos",
      "Plano de fidelização com descontos",
    ],
  },
];