export enum StatusRequest {
  PENDING = 'PENDENTE',
  IN_REVIEW = 'EM_ANALISE',
  PLAN_OFFERED = 'PLANO_OFERECIDO',
  CONTRACT_GENERATED = 'CONTRATO_GERADO',
  COMPLETED = 'CONCLUIDO',
  REJECTED = 'REJEITADO',
}